#:schema node_modules/wrangler/config-schema.json
name = "s3-access-worker"
main = "src/index.ts"
compatibility_date = "2024-11-06"
workers_dev = false

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
bucketURL='https://{YOUR_ACCOUNT_ID}.r2.cloudflarestorage.com/{YOURBUCKET}' # this is the bucket endpoint
# accessKeyId= YOUR KEY AS SECRET
# secretAccessKey= YOUR KEY AS SECRET